[package]
name = "wagen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasm-encoder = "0.29.0"
extism = {version = "0.4.0", optional = true}
wasmtime = {version = "8.0.0", optional = true}
wasmparser = {version = "0.107.0", optional = true}

[features]
default = ["extism", "wasmtime", "parser"]
parser = ["wasmparser"]

[[example]]
name = "add1"
required-features = ["wasmtime"]

[[example]]
name = "count_vowels"
required-features = ["extism"]

[[example]]
name = "hello"
required-features = ["extism"]
