[package]
name = "wagen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasm-encoder = "0.36.0"
extism-manifest = {git = "https://github.com/extism/extism", optional = true}
extism = {git = "https://github.com/extism/extism", optional = true}
wasmtime = {version = "14.0.0", optional = true}
wasmparser = {version = "0.116.0", optional = true}

[features]
default = ["parser", "runtime"]
runtime = ["extism", "wasmtime", "extism-manifest"]
parser = ["wasmparser"]

[[example]]
name = "add1"
required-features = ["wasmtime"]

[[example]]
name = "count_vowels"
required-features = ["extism"]

[[example]]
name = "hello"
required-features = ["extism"]
