[package]
name = "wagen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasm-encoder = {version = "0.38.0", features = ["wasmparser"]}
extism-manifest = {git = "https://github.com/extism/extism", optional = true}
extism = {git = "https://github.com/extism/extism", optional = true}
wasmtime = {version = "16.0.0", optional = true}
wasmparser = {version = "0.118.0", optional = true}

[features]
default = ["runtime", "wasmparser"]
runtime = ["extism", "wasmtime", "extism-manifest"]

[[example]]
name = "add1"
required-features = ["wasmtime"]

[[example]]
name = "count_vowels"
required-features = ["extism"]

[[example]]
name = "hello"
required-features = ["extism"]
