name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --features extism,wasmtime
    - name: Build examples
      run: cargo build --examples --features extism,wasmtime
    - run: cargo run --example add1 --features extism,wasmtime
    - run: cargo run --example count_vowels --features extism,wasmtime
